name: Azure Static Web Apps CI/CD

# Déclenchement : à chaque push ou PR sur main
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    permissions:
      id-token: write     # nécessaire si tu utilises OIDC (facultatif ici)
      contents: read

    steps:
      # Récupère les sources
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Étape de déploiement vers Azure Static Web App
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Jeton de déploiement stocké dans GitHub → Settings → Secrets → Actions
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}

          action: upload             # simple copie des fichiers
          app_location: "/"          # tes fichiers (index.html, voisins.js, …) sont à la racine
          api_location: ""           # pas d'API dans ce repo
          output_location: ""        # vide : pas de dossier de build
          skip_app_build: true       # DÉSACTIVE complètement la phase de build

  # Ferme automatiquement le déploiement de pull-request une fois la PR close
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: close_pr
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
